//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client2.PetShop {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:dm:wcf:labs:architecure", ConfigurationName="PetShop.PetShopOrderContract")]
    public interface PetShopOrderContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="PlaceOrder", ReplyAction="PlaceOrderReply")]
        void PlaceOrder(string orderData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PetShopOrderContractChannel : Client2.PetShop.PetShopOrderContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PetShopOrderContractClient : System.ServiceModel.ClientBase<Client2.PetShop.PetShopOrderContract>, Client2.PetShop.PetShopOrderContract {
        
        public PetShopOrderContractClient() {
        }
        
        public PetShopOrderContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PetShopOrderContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PetShopOrderContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PetShopOrderContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PlaceOrder(string orderData) {
            base.Channel.PlaceOrder(orderData);
        }
    }
}
